# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6763362570fd8e470fcddd7246cede0aef8e5baea8af52b7176f0114e5447ddb30fea4f8cf1de7c5a2e3c7bcd21df5445d664b917d891ba7238b4791f0bd0e3

test:
  secret_key_base: 3000ec32533bd546e9d00648feec90fb494597cfb57d48847509be28f668698851554512560a133a8f5895f66c8b27e675f1de9d0cbc2c7e7323512fc38ae686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
